-- Auto-generated from schema-map-postgres.psd1 (map@62c9c93)
-- engine: postgres
-- table:  merkle_roots
CREATE TABLE IF NOT EXISTS merkle_roots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_table VARCHAR(64) NOT NULL,
  period_start TIMESTAMPTZ(6) NOT NULL,
  period_end   TIMESTAMPTZ(6) NOT NULL,
  root_hash BYTEA NOT NULL,
  proof_uri VARCHAR(512),
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  leaf_count BIGINT NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_merkle_subject_period UNIQUE (subject_table, period_start, period_end)
);
